// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDesarrolloServiciosWeb.DataAccess.Data;

#nullable disable

namespace ProyectoDesarrolloServiciosWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230516002542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoDesarrolloServiciosWeb.Models.Categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategoria"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("idCategoria");

                    b.ToTable("categorias");

                    b.HasData(
                        new
                        {
                            idCategoria = 1,
                            DisplayOrder = 1,
                            nombre = "Hamburguesas"
                        },
                        new
                        {
                            idCategoria = 2,
                            DisplayOrder = 2,
                            nombre = "Pizas"
                        },
                        new
                        {
                            idCategoria = 3,
                            DisplayOrder = 3,
                            nombre = "Papas"
                        });
                });

            modelBuilder.Entity("ProyectoDesarrolloServiciosWeb.Models.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProducto"));

                    b.Property<int>("categoriaId")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreProducto")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("idProducto");

                    b.HasIndex("categoriaId");

                    b.ToTable("producto");

                    b.HasData(
                        new
                        {
                            idProducto = 1,
                            categoriaId = 1,
                            descripcion = "Deliciosas hamburguesas con papas",
                            nombreProducto = "Hamburguesas",
                            precio = 50.0
                        },
                        new
                        {
                            idProducto = 2,
                            categoriaId = 1,
                            descripcion = "Deliciosas hamburguesas con papas",
                            nombreProducto = "Hamburguesas",
                            precio = 50.0
                        },
                        new
                        {
                            idProducto = 3,
                            categoriaId = 1,
                            descripcion = "Deliciosas hamburguesas con papas",
                            nombreProducto = "Hamburguesas",
                            precio = 50.0
                        },
                        new
                        {
                            idProducto = 4,
                            categoriaId = 1,
                            descripcion = "Deliciosas hamburguesas con papas",
                            nombreProducto = "Hamburguesas",
                            precio = 50.0
                        });
                });

            modelBuilder.Entity("ProyectoDesarrolloServiciosWeb.Models.Producto", b =>
                {
                    b.HasOne("ProyectoDesarrolloServiciosWeb.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
